"""change cache fetched_at to datetime

Revision ID: 260c04c71949
Revises: 19d6211d5131
Create Date: 2026-06-14 14:41:39.586588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '260c04c71949'
down_revision: Union[str, Sequence[str], None] = '19d6211d5131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cache', 'fetched_at',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cache', 'fetched_at',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
