"""cache raw json

Revision ID: 27b1adba37d6
Revises: 260c04c71949
Create Date: 2026-06-14 15:04:56.998427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b1adba37d6'
down_revision: Union[str, Sequence[str], None] = '260c04c71949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cache', sa.Column('raw_response_json', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cache', 'raw_response_json')
    # ### end Alembic commands ###
