"""remove raw response from cache

Revision ID: 3d6589276c32
Revises: d25b515ce5c1
Create Date: 2026-06-14 15:24:11.366227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d6589276c32'
down_revision: Union[str, Sequence[str], None] = 'd25b515ce5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cache', 'articles_json',
               existing_type=mysql.TEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.drop_column('cache', 'raw_response_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cache', sa.Column('raw_response_json', mysql.TEXT(), nullable=False))
    op.alter_column('cache', 'articles_json',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
